### PR TITLE
Add "unified_mode"

### PR DESCRIPTION
**Pull request by imchanhtin**
Add `unified_mode true` to remove deprecation messages

### CODE REVIEW

**Review by Annih — APPROVED** [review]

**Comment by Annih** [comment]
OK tests are not able to run from a different origin repo. Anyway LGM

**Comment by Annih** [comment]
Thanks @imchanhtin

**Comment by Annih** [comment]
However I won't be able to do a release soonish, please be patient.

**Comment by imchanhtin** [comment]
Thanks for your review, @Annih

**Comment by imchanhtin** [comment]
Hi @Annih, do we have any plan to release the new version of this cookbook? Because wsus-client is the important cookbook for my service, so I need to update my service for the new release when It ready.

**Pull request merged**
