### PR TITLE
Explicitly set detection_frequency to 22 hours

### PR DESCRIPTION
**Pull request by Annih**

### CODE REVIEW

**Comment by rveznaver** [comment]
Could you add a comment explicitly stating _why_ we set the frequency to 22h?

**Comment by Annih** [comment]
Don't you think the comment 2 lines above isn't enough?

>  0          = disables custom detection frequency (use default value of 22 hours)

22 hours is Microsoft default value

**Comment by rveznaver** [comment]
I didn't understand from the context that it is a Microsoft default value (I thought it was the cookbook default value). So could you just add "Microsoft" or "Windows" in front to make it less confusing?

**Comment by Annih** [comment]
done :)

**Comment by rveznaver** [comment]
+1

**Pull request merged**
